### ISSUE TITLE
Can't search for tags with spaces

### ISSUE THREAD

**Issue by kanzure** [davidlazar/jotmuch#3]
Consider making a bookmark:

```
$ jot bookmark https://github.com/davidlazar/jotmuch "white space"
```

Tags with whitespace don't seem to be returned by search:

```
$ jot search tag:"white space"
```

At minimum, the docs should mention the workaround (if any), or this may be an actual bug possibly fixed with escape characters.

**Comment by davidlazar** [comment]
Your shell is probably interpreting the quotes. Try escaping the quotes:

```
$ jot search tag:\"white space\"
```

**Comment by kanzure** [comment]
Weird, I even mentioned escaping. So either I didn't try escaping at all, or I had picked a bad test case. I probably tried tag:\'white space\'. Oh well.
